project:
  type: website
  output-dir: docs
  render:
  - index.qmd
  - /posts/*

website:
  title: "Klinkenberg"
  navbar:
    right:
      - href: index.qmd#research
        text: Research
      - href: index.qmd#blog-posts
        text: Blog

format:
  html:
    theme: cosmo
    smooth-scroll: true